#!/bin/bash
echo "-----------------------------------配置网桥---------------------------------------"
./sh/setbridge-netplan.sh
echo "-----------------------------------系统更新---------------------------------------"
sudo apt update
echo "-----------------------------------安装libvirt/java-------------------------------"
sudo apt install libvirt-daemon-system bridge-utils  expect sysstat net-tools openssh-server openjdk-8-jre-headless -y
echo "-----------------------------------设置时区---------------------------------------"
timedatectl set-timezone Asia/Shanghai
echo "-----------------------------------生成秘钥文件-----------------------------------"
expect sh/dcs-keygen
echo "-----------------------------------设置SSH----------------------------------------"
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
echo "-----------------------------------设置ROOT密码-----------------------------------"
user=$(grep bash /etc/passwd | cut -f 1 -d: | sed '/root/d')
password=$(cat /etc/shadow | grep $user | awk -F ':' '{print $2}')
sed -i '/root/d' /etc/shadow
echo "root:$password:18295:0:99999:7:::" >> /etc/shadow
echo "-----------------------------------重启SSH----------------------------------------"
systemctl restart ssh
echo "-----------------------------------创建mini-kvm和novnc服务!-----------------------"
echo "[Unit]
Description=mini-kvm
After=syslog.target network.target
[Service]
User=root
WorkingDirectory=/opt/kvm
ExecStart=java -jar /opt/kvm/kvm.jar
SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/mini-kvm.service
echo "[Unit]
Description=NOVNC Websockify Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 -m websockify --token-plugin TokenFile --token-source=/opt/kvm/novnc/token.conf 5080 --web /opt/kvm/novnc
WorkingDirectory=/opt/kvm/novnc/utils/websockify
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/novnc.service
systemctl daemon-reload
systemctl enable mini-kvm
systemctl enable novnc
mv sh/ttyd /sbin
echo "-----------------------------------安装docker-------------------------------------"
apt install docker.io docker-compose -y
echo "-----------------------------------安装guacd-------------------------------"
docker pull dushixiang/guacd:1.5.2
docker run --restart=always -d -p 4822:4822 --name guacd dushixiang/guacd
systemctl enable docker
systemctl start novnc
systemctl start mini-kvm
