#!/usr/bin/expect
spawn ssh-keygen
expect {    
     "*/.ssh/id_rsa):" {        
             send "\n";        
             exp_continue;    
                }    
     "*(empty for no passphrase):" {        
             send "\n";        
             exp_continue;    
             }
     "*passphrase again:" {        
             send "\n";        
             exp_continue;    
             }
       }
